package com.zhide.app.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 


import java.util.List;

public class NewsModel {
    private int code;
    private String message;
    private List<NewsData> data;

    public int getCode() {
        return code;
    }

    public void setCode(int code) {
        this.code = code;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public List<NewsData> getData() {
        return data;
    }

    public void setData(List<NewsData> data) {
        this.data = data;
    }

    public class NewsData {
        private long NI_Id;
        private String NI_Title;//标题
        private String NI_Summary;//内容简介，若列表中需要显示部分文字，则使用该字段
        private String NI_Url;//H5的页面链接，APP端打开内容页时直接访问这个H5的页面链接
        private String NI_Index;//顺序号
        private String NI_UpdateTime;//更新时间

        public long getNI_Id() {
            return NI_Id;
        }

        public void setNI_Id(long NI_Id) {
            this.NI_Id = NI_Id;
        }

        public String getNI_Title() {
            return NI_Title;
        }

        public void setNI_Title(String NI_Title) {
            this.NI_Title = NI_Title;
        }

        public String getNI_Summary() {
            return NI_Summary;
        }

        public void setNI_Summary(String NI_Summary) {
            this.NI_Summary = NI_Summary;
        }

        public String getNI_Url() {
            return NI_Url;
        }

        public void setNI_Url(String NI_Url) {
            this.NI_Url = NI_Url;
        }

        public String getNI_Index() {
            return NI_Index;
        }

        public void setNI_Index(String NI_Index) {
            this.NI_Index = NI_Index;
        }

        public String getNI_UpdateTime() {
            return NI_UpdateTime;
        }

        public void setNI_UpdateTime(String NI_UpdateTime) {
            this.NI_UpdateTime = NI_UpdateTime;
        }
    }
}
